[package]
authors = ["Meta"]
description = "Implementation of derive(Allocative) for allocative crate"
documentation = "https://docs.rs/allocative"
edition = "2021"
license = { workspace = true }
name = "allocative_derive"
repository = "https://github.com/facebookexperimental/allocative"
version = "0.3.3"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = { workspace = true }
quote = { workspace = true }
syn = { workspace = true }
